version: '2'
  
services:
  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000
    volumes:
      - /srv/data/docker/registry:/var/lib/registry
      
