version: '3.4'

services:
  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
    volumes:
      - /srv/data/docker/registry/registry:/var/lib/registry
      - /srv/data/docker/registry/certs:/certs      
