version: '3.4'

services:
  registry:
    image: registry:2
    restart: always
    hotname: registry
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_HTTP_SECRET: 
    volumes:
      - /srv/data/docker/registry/registry:/var/lib/registry
      - /srv/data/docker/registry/certs:/certs

  ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 40443:443
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENV_USE_SSL: yes
    volumes:
      - /srv/data/docker/registry/certs/registry.crt:/etc/apache2/server.crt:ro
      - /srv/data/docker/registry/certs/registry.key:/etc/apache2/server.key:ro
  
